### PR TITLE
Fix auto advance after timing markers change

### LINKED ISSUE #164: Auto advance sometimes just doesn’t.
Sometimes (seemingly arbitrarily) the player finishes playing, but doesn’t auto advance when it’s supposed to.

### PR DESCRIPTION
**Pull request by mstratford**
Fixes #164.

### CODE REVIEW

File: src/mixer/state.ts [hunk 1]
```diff
@@ -498,7 +498,17 @@ export const load = (
...
+          // since the player's idea of an item may be changed over it's lifecycle (setting intro/cue/outro etc.)
+          // Therefore we'll find the updated item from the plan and match that.
+          const itsChannelItem = itsChannel.filter(
+            (x) => itemId(x) === itemId(item)
+          );
+          if (itsChannelItem.length !== 1) {
+            // Somehow we've got 0 or multiple identical timeslotitems (or ghosts), bail out!
+            return;
+          }
+          const itsIndex = itsChannel.indexOf(itsChannelItem[0]);
```
Comment (markspolakovs) [inline src/mixer/state.ts:511]: Have you considered `itsChannel.findIndex(x => itemId(x) === itemId(item))`?

Comment (mstratford) [reply src/mixer/state.ts]: I have now 👍

**Review by markspolakovs — APPROVED** [review]
